apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    env:
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "no"
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    ports:
    - containerPort: 3306
      name: mysql

