apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: webapp
spec:
  containers:
  - name: webapp
    image: 553085735006.dkr.ecr.us-east-1.amazonaws.com/linyi:application
    ports:
    - containerPort: 8080
    env:
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DATABASE
      value: "employees"
    - name: DBPWD
      value: "pw"
    - name: DBHOST
      value: "mysql-service.mysql.svc.cluster.local"
